[package]
name = "circuits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "nova"
path = "src/lib.rs"

[dependencies]
nova-scotia = "0.4.0"
nova-snark = { version = "0.21.0", default-features = false }
serde = "1.0"
serde_json = "1.0.96"
ff = { version = "0.13", features = ["derive"]}
pasta_curves = "0.5.1"
nova_macro = { path = "nova_macro" }
nova_macro_derive = { path = "nova_macro/nova_macro_derive" }
